###
POST {{nginx}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "1234",
  "mail": "",
  "method": "passwd",
  "checkCode": "",
  "checkCodeKey": ""
}


###
GET {{gateway}}/content/category/list
Authorization:Bearer eyJraWQiOiJ5aXhpYW8iLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ5aXhpYW8iLCJzdWIiOiJhZG1pbiIsImFjY2VzcyI6ImFkbWluIiwiZXhwIjoxNzc0MjcxOTU0LCJpYXQiOjE3NzQyNjgzNTR9.hFmBxFaFIg4KCArJ__1tFj490yD-3_AOf18hUWz_XWtbivweY9hbBtAGrcm6gd4YUkRtvrRXaQ8oJCPeak-reoOsdBTQqtp-hHU6tZmmqNHXCVsQhcqpSd3toemZu2LxPwCOF4Fl_jIZsb1z_Kn0rK2euSUwXXQ-aXg7_5T4AAsyBrfKFT146DIwnnyXCPP6EYHqQNzYJibOZXKVerNP6z6GMp7gw9W8CnxLgBOzll4SYE_zicpLqb8F1OtDITIPUGp-UFT8yXz0-ydp-3XXkqb3-mGkTV7OR2GY9xJ2teecs2Sf-0vh25QfBs0vnIl7HlTAGK0IaSLO_FyvsF9NWw

###
GET {{gateway}}/sms/captcha/create


###
POST {{gateway}}/auth/user/register
Content-Type: application/json

{
  "name": "hls",
  "avatarId": 12,
  "avatarUrl": "asdasdasdasdasdasdasd",
  "sex": "男",
  "account": "asdsadfsdfsefsr",
  "passwd": "sefwefer"
}
