###
POST {{nginx}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "1234",
  "mail": "",
  "method": "passwd",
  "checkCode": "",
  "checkCodeKey": ""
}


###
GET {{gateway}}/content/category/list
Authorization:Bearer eyJraWQiOiJ5aXhpYW8iLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ5aXhpYW8iLCJzdWIiOiJ5aXhpYW8iLCJhY2Nlc3MiOiJhZG1pbiIsImlkIjoxLCJleHAiOjE3NzY2NjUzODgsImlhdCI6MTc3NjY2MTc4OH0.S26AS8srFc937Ji2ZzPe0KYeoI8-JiKFtqguSqmvzpo8dCpzKfmG5BnBAkxn4FzQQD0EBpv9tvObWyGfq88s8dcMZfCvIBVT2EqNvQd1JPu2TLZ_xipE7ZFou8VnVpQCFuqkCiphcOP_mzFqvFhag73UFPJ7Ujd51YI2f45EwRA2GxB2eRLaD6OPgMz8LlX089X9EXkRdM0_eJtWHSrk3gMlcQRA06wiDkf3uFVmrOpC2Nbp7b3qOGWsXsNKw3atohhibKUyYun423jF8dv2ZY-ez6lFePSyoSv3Ud45rxW-T65mYelxElGERKGtEvGl2horQI4ByeKBqq2qIHHsbQ



###
GET {{gateway}}/sms/captcha/create


###
POST {{gateway}}/auth/user/register
Content-Type: application/json

{
  "name": "hls",
  "avatarId": 12,
  "avatarUrl": "asdasdasdasdasdasdasd",
  "sex": "男",
  "account": "asdsadfsdfsefsr",
  "passwd": "sefwefer"
}
